### ISSUE TITLE
Android app crashes after leaving the page containing Unity

### ISSUE THREAD

**Issue by assemmarwan** [snowballdigital/flutter-unity-view-widget#80] opened 2019-11-19 09:53 UTC
This issue happens where when I leave the page where Unity was running. The app navigates back and in a second or so, the app closes. In the console, this is what is printed before it crashes.

```
E/Unity   (21792): [XRInputSubsystem] A device disconnection with the id 0 has been reported but no device with that id was connected. 
E/Unity   (21792): (Filename:  Line: 320)
E/Unity   (21792): 
I/native  (21792): arpresto_api.cc:145 ArPresto::ArPresto_setEnabled
I/native  (21792): session.cc:1113 Entering Session::Pause.
W/native  (21792): calibration_convergence_detector_utils.cc:142 Failed to get calibration qualification statistics: States are empty.
I/native  (21792): online_calibration_manager.cc:126 OnlineCalibrationManager: Discarding the new online recalibration estimates.
I/native  (21792): cameras.cc:1249 Camera changed state from CAPTURING to STOPPING: Camera 0: State CAPTURING: Capture session stopping...
E/ACameraDevice(21792): onDeviceIdle sending state cb
I/native  (21792): android_camera.cc:1531 Camera 0: State STOPPING: Camera completed repeating capture sequence 0
I/native  (21792): cameras.cc:1249 Camera changed state from STOPPING to OPEN: Camera 0: State STOPPING: Camera stopped.
I/native  (21792): cameras.cc:1249 Camera changed state from OPEN to CLOSED: Camera 0: State OPEN: Camera device closed successfully.
I/native  (21792): session.cc:1204 Session::PauseWithAnalytics returning OK.
I/native  (21792): session_manager.cc:223 ArPresto::Moving from ArPrestoStatus 101 to 102
E/Unity   (21792): ArgumentNullException: Value cannot be null.
E/Unity   (21792): Parameter name: _unity_self
E/Unity   (21792): 
E/Unity   (21792):  
E/Unity   (21792): (Filename: currently not available on il2cpp Line: -1)
E/Unity   (21792): 
E/Unity   (21792): NullReferenceException: Object reference not set to an instance of an object.
E/Unity   (21792):   at ARLocation.PlaceAtLocation.RemoveLocationProviderListeners () [0x00000] in <00000000000000000000000000000000>:0 
E/Unity   (21792):  
E/Unity   (21792): (Filename: currently not available on il2cpp Line: -1)
E/Unity   (21792): 
D/        (21792): PlayerBase::stop() from IPlayer
D/AudioTrack(21792): stop() called with 568320 frames delivered
I/Process (21792): Sending signal. PID: 21792 SIG: 9
```

I have tried calling `pause()` in `dispose()` as follows, but gives the same result.

```dart
  @override
  void dispose() {
    _unityWidgetController.pause();
    super.dispose();
    print("Called dispose");
  }
```

I must point out that all functionalities are fine, posting messages, receiving messages, and the AR scene works fine. I must also mention that this is exclusive to Android.

I have read that there's unload() function which I implemented in my fork, but same result :( 

Your help is highly appreciated :)

**Comment by thomas-stockx** [comment] 2019-11-19 10:00
This is probably a duplicate of #46, caused by unityPlayer.quit().

@juicycleff was supposedly looking into that issue.

**Closed by thomas-stockx** 2019-11-19 10:00 UTC
